- name: NVM - Installing NVM
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: NVM - Configure for zsh Part 1
  lineinfile: 
    path: "{{ansible_env.HOME}}/.zshrc"
    line: 'export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")'

- name: NVM - Configure for zsh Part 2
  lineinfile: 
    path: "{{ansible_env.HOME}}/.zshrc"
    line: '"[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm'
    
- name: NVM - Configure for bash Part 1
  lineinfile: 
    path: "{{ansible_env.HOME}}/.bashrc"
    line: 'export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")'

- name: NVM - Configure for bash Part 2
  lineinfile: 
    path: "{{ansible_env.HOME}}/.bashrc"
    line: '"[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm'
    

