- name: DNF - Update packages
  dnf:
    name: "*"
    state: latest
  become: yes  


- name: DNF - Install the 'Development tools' package group
  dnf:
    name: "{{ dnf.packages }}"
    state: present
  become: yes

- name: DNF - Install packages
  dnf:
    name: "{{ dnf.packages }}"
    state: present
  become: yes

- name: DNF - Install packages
  dnf:
    name: "{{ dnf.packages }}"
    state: present
  become: yes

