- name: APT - Change mirror address
  become: yes
  replace:
    path: /etc/apt/sources.list        
    regexp: 'http:\/\/us\.archive\.ubuntu\.com\/ubuntu\/'
    replace: 'http://ubuntu.mirror.iweb.ca/'
    backup: yes

- name: APT - Update repositories cache
  apt:
    update_cache: yes
  become: yes

- name: APT - Update packages
  apt:
    upgrade: full
  become: yes  

- name: APT - Install packages
  apt:
    name: "{{ apt.packages }}"  
  become: yes

- name: Flatpak - Install package
  flatpak:
    name: "{{ item }}"
    state: present
    method: "{{ flatpak.method }}"
  with_items: "{{ flatpak.packages }}"

- name: Docker - Add apt key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  become: yes

- name: Docker - Add PPA
  shell: | 
   add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
     $(lsb_release -cs) \
     stable"
  become: yes

- name: Docker - Update APT repositories cache
  apt:
    update_cache: yes
  become: yes

- name: Docker - Install Docker packages
  apt:
    name: "{{ item }}"
  with_items: "{{ docker.packages }}"
  become: yes

- name: Docker - Add current user to docker group
  shell: sudo usermod -aG docker $USER
  become: yes
