apt:
    packages:
        - "htop"
        - "zsh"
        - "powertop"
        - "virtualbox"
        - "lutris"
        - "steam-installer"
        - "python3"
        - "python3-pip"
        - "python3-virtualenv"
        - "apt-transport-https"
        - "ca-certificates"
        - "curl"
        - "gnupg-agent"
        - "software-properties-common"
        - "git"

flatpak:
    source: flathub
    method: user

    packages:
        - "com.spotify.Client"
        - "com.visualstudio.code"
        - "org.gnome.Games"
        - "com.slack.Slack"
        - "com.discordapp.Discord"

docker:
    packages:
        - "docker-ce"
        - "docker-ce-cli"
        - "containerd.io"
nvm:
    config: 'export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm'